### ISSUE TITLE
Static executable

### ISSUE THREAD

**Issue by AsparaGus116** [SortedIvan/dfamaker#1]
I tried to build this project using VS2022, but I got some issues with the final executable in that it seems there are missing dlls. It would be helpful to configure the project for static linking, or at least to include a static executable. This would be very helpful and I would be very happy to recommend this software. Thanks!

**Comment by AsparaGus116** [comment]
[Uploading Release.zip…]()
I compiled it, can you add this as a release in the meantime?

**Comment by SortedIvan** [comment]
Hi August,

Not home until the end of the week. I have been working on an udpated
version using ImGui as the base for UI. Can let you know when that is good
for use.

In the meantime, did you figure out how to get a simple DFA going? I
believe the public version I have on my github has quite a lot of issues. I
don't think files are usable either.

Let me know if you need any help.

Ivan

**Comment by AsparaGus116** [comment]
Hi Ivan,I got everything working, but was unable to figure out how to change a state to an accept state. How would I go about this?AugustOn Oct 7, 2024, at 5:11 PM, Ivan Ovcharov ***@***.***> wrote:﻿
Hi August,



Not home until the end of the week. I have been working on an udpated

version using ImGui as the base for UI. Can let you know when that is good

for use.



In the meantime, did you figure out how to get a simple DFA going? I

believe the public version I have on my github has quite a lot of issues. I

don't think files are usable either.



Let me know if you need any help.



Ivan



On Mon, Oct 7, 2024, 9:25 PM August Bresnaider ***@***.***>

wrote:

**Comment by SortedIvan** [comment]
Double click the state you'd like to make accepting. Should be double
circled once you do so. To make it back to non-accepting, double click
again.
